[Doc] Create STSELib documentation
STMicroelectronics/STSELib pull request #29
Opened 2024-09-30 13:46 UTC by Grom-

2024-10-01 08:32 UTC, Vaarai requested changes
As a gereral feedback I strongly recommend to replace all `STSAFE*` occurences in `API/` layer.

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_device_authenticate.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_device_authenticate.dox
> +		printf("\n\n\r ## Device authentication over ST SPL05 CA certificate : Successful\n\r");
Remove mention to a specific certificate as it may change in the future

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_certificate.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-Axxx device during the API execution
Replace STSAFE-Axxx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_certificate.dox
> +        HOST -> STSAFE : read_data_zone(zone 0, CERTIFICATE_SIZE_OFFSET_BYTES,CERTIFICATE_SIZE_LENGTH,NO_CHUNK,NO_PROT )
Replace STSAFE by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_certificate_size.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_certificate.dox
> +\sa stsafe_echo()
Replace `stsafe_echo()` by `stse_echo()`

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_certificate_size.dox
> +\sa stsafe_init()
Replace `stsafe_init()` by `stse_init()`

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_id.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_authentication/stse_get_device_id.dox
> +\sa stsafe_echo()
Replace `stsafe_echo()` by `stse_echo()`

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_echo.dox
Replace all `STSAFE` by `STSE` as it is an API layer file

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_get_command_AC.dox
> +\n Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_get_command_AC.dox
> +	stsafe_se_get_command_AC_count(&stsafe_handler, &cmd_authorization_record_count);
I'm not sure, but is this replacable by `stse_se_get_command_AC_count()`

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_get_command_AC.dox
> +	stsafe_ret = stsafe_se_get_command_AC(&stsafe_handler,
I'm not sure, but is this replacable by `stse_se_get_command_AC()

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_get_command_AC.dox
> +\sa stsafe_query()
Could we remove this `see also` entry ?

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_lock.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_lock.dox
> +    PLAT_UI8 password[STSAFE_PASSWORD_LENGTH] = { /* password value set during device personalization*/ };
Replace STSAFE by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_power_on.dox
> +    stse_ret = stse_set_default_handler_value(&stse_handler);
Missing `stse_handler` declaration

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_power_on.dox
>      stsafe_ReturnCode_t stsafe_ret;
Replace `stsafe_ret` by `stse_ret`

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_unlock.dox
> +    PLAT_UI8 password[STSAFE_PASSWORD_LENGTH] = { /* password value set during device personalization*/ };
Replace STSAFE by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_device_unlock.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/APIs/device_management/stse_init.dox
> +Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Replace STSAFE-A1xx by STSE

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/dox_files/Services/stsafe_verify_password.dox
>      participant "STSAFE-Axxx" as STSAFE
Replace by:
```C
participant "STSE" as STSE
```

2024-10-01 08:32 UTC, Vaarai commented on doc/resources/doxygen-awesome/LICENSE
doxygen-awesome is a separate module, STSELib require an SBOM

2024-10-01 08:32 UTC, Vaarai commented on services/stsafea/stsafea_aes.h
> +/*! \defgroup stsafea_aes STSAFE AES services
STSAFE`-A` AES services

2024-10-01 08:32 UTC, Vaarai commented on services/stsafea/stsafea_data_partition.h
> +/*! \defgroup stsafe_data_partition STSAFE-A Data partition management
`stsafe_data_partition` => `stsafea_data_partition`

2024-10-01 08:49 UTC, Grom- commented on services/stsafea/stsafea_data_partition.h
> +/*! \defgroup stsafe_data_partition STSAFE-A Data partition management
Updated

2024-10-02 11:08 UTC, Vaarai requested changes
Added few comments and some comments remains from previous review.

STSAFE keyword is still used in API layer where it should be replaced by STSE.

2024-10-02 11:08 UTC, Vaarai commented on api/stse_device_authentication.c
> + * \brief   STSE uthentication API (sources)
STSE `A`uthentication

2024-10-02 11:08 UTC, Vaarai commented on core/stse_device.h
> + * \return \ref stse_ReturnCode_t : STSE_OK on success ; error code otherwise
New std format is : `\ref STSE_OK on success ; \ref stse_ReturnCode_t error code otherwise`

2024-10-02 11:08 UTC, Vaarai commented on doc/resources/dox_files/APIs/__template.dox
As this file is a template I think `\sa stsafe_init` should be replaced by `\sa stse_init`

2024-10-02 11:08 UTC, Vaarai commented on doc/resources/dox_files/APIs/symmetric_key_management/stse_write_symmetric_key_wrapped_authenticated.dox
This file is a duplicate of `stse_write_symmetric_key_wrapped.dox`, description/diagrams do not correspond.

2024-10-02 11:08 UTC, Vaarai commented on doc/resources/dox_files/Core/__template.dox
As this file is a template I think `\sa stsafe_init` should be replaced by `\sa stse_init`

2024-10-02 11:08 UTC, Vaarai commented on doc/resources/dox_files/Services/__template.dox
As this file is a template I think `\sa stsafe_init` should be replaced by `\sa stse_init`

2024-10-02 11:08 UTC, Vaarai commented on services/stsafea/stsafea_sessions.h
> + * \return \ref stsafe_ReturnCode_t : STSE_OK on success ; error code otherwise
New std format is: `\ref STSE_OK on success ; \ref stse_ReturnCode_t error code otherwise`

2024-10-02 11:08 UTC, Vaarai commented on services/stsafea/stsafea_sessions.h
> + * \return \ref stsafe_ReturnCode_t : STSE_OK on success ; error code otherwise
New std format is: `\ref STSE_OK on success ; \ref stse_ReturnCode_t error code otherwise`

2024-10-02 11:08 UTC, Vaarai commented on services/stsafea/stsafea_sessions.h
> + * \return \ref stsafe_ReturnCode_t : STSE_OK on success ; error code otherwise
New std format is: `\ref STSE_OK on success ; \ref stse_ReturnCode_t error code otherwise`

2024-10-24 12:37 UTC, Grom- commented on doc/resources/dox_files/APIs/device_authentication/stse_device_authenticate.dox
> +		printf("\n\n\r ## Device authentication over ST SPL05 CA certificate : Successful\n\r");
Done

2024-10-24 12:39 UTC, Grom- commented on doc/resources/dox_files/Services/stsafe_verify_password.dox
>      participant "STSAFE-Axxx" as STSAFE
We are in the STSAFE-A service layer

2024-10-24 12:40 UTC, Grom- commented on services/stsafea/stsafea_aes.h
> +/*! \defgroup stsafea_aes STSAFE AES services
Done

2024-10-24 12:41 UTC, Grom- commented on api/stse_device_authentication.c
> + * \brief   STSE uthentication API (sources)
Done

2024-10-24 12:45 UTC, Grom- commented on doc/resources/dox_files/Core/__template.dox
Done

2024-10-24 12:49 UTC, Grom- commented on services/stsafea/stsafea_sessions.h
> + * \return \ref stsafe_ReturnCode_t : STSE_OK on success ; error code otherwise
Done

2024-10-24 12:49 UTC, Grom- commented on services/stsafea/stsafea_sessions.h
> + * \return \ref stsafe_ReturnCode_t : STSE_OK on success ; error code otherwise
Done

2024-10-24 13:07 UTC, Vaarai approved these changes
Good job !!!

2024-10-24 13:07 UTC, merged

2024-10-24 13:08 UTC, Vaarai commented
PR merged, @Grom-  you can delete your branch safely.